//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAPIThree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotPlant
    {
        public int Id { get; set; }
        public string PotName { get; set; }
        public Nullable<int> PotCategory { get; set; }
        public Nullable<int> PotColor { get; set; }
        public Nullable<int> PotSize { get; set; }
        public Nullable<int> PotPrice { get; set; }
    }
}
